### ISSUE TITLE
Processing multiple images creates duplicates

### ISSUE THREAD

**Issue by BurtonShane** [idesis-gmbh/png2icons#7]
Version: png2icons v2.0.0

I think this is an issue with the caching added in the recent version. 

I use the png2icons API in a build script where we convert a few images to .ico files. However, some of these images are nearly, but not quite identical (icon, and then icon with notification dot overlay). 

When using png2icons, it processes the first image fine, but then when it gets to the second it just reuses the result from the first image, so the converted ico files end up being identical.

**Comment by mn4367** [comment]
You're right. This fixed in version 2.0.1. Thank you very much for letting me know!
